version: "3.8"

services:
  mongopredi:
    image: mongo:7.0
    container_name: mongopredi
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - mongo_net

  users-service:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongopredi:27017
    depends_on:
      - mongopredi
    networks:
      - mongo_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mongo_net

volumes:
  mongodata:

networks:
  mongo_net:
