version: "3.8"

services:
  mongopredi:
    image: mongo:latest
    container_name: mongopredi
    ports:
      - "27017:27017"
    networks:
      - backend

  users-service:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: users-service
    ports:
      - "8080:8080"
    depends_on:
      - mongopredi
    environment:
      - MONGO_URI=mongodb://mongopredi:27017
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - users-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
