version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=${ENV}
      - JWT_SECRET=${JWT_SECRET}
      - USERS_SERVICE_URL=http://users:${PORT_USERS}
      - DRIVERS_SERVICE_URL=http://drivers:${PORT_DRIVERS}
      - PRODES_SERVICE_URL=http://prodes:${PORT_PRODES}
      - RESULTS_SERVICE_URL=http://results:${PORT_RESULTS}
      - SESSIONS_SERVICE_URL=http://sessions:${PORT_SESSIONS}
      - GROUPS_SERVICE_URL=http://groups:${PORT_GROUPS}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    depends_on:
      - users
      - drivers
      - prodes
      - results
      - sessions
      - groups

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT_USERS}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${PORT_USERS}:${PORT_USERS}"
    depends_on:
      - db

  sessions:
    build:
      context: ./sessions
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT_SESSIONS}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${PORT_SESSIONS}:${PORT_SESSIONS}"
    depends_on:
      - db

  results:
    build:
      context: ./results
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT_RESULTS}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${PORT_RESULTS}:${PORT_RESULTS}"
    depends_on:
      - db
      - sessions

  prodes:
    build:
      context: ./prodes
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT_PRODES}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SESSIONS_URL=http://sessions:${PORT_SESSIONS}
      - USERS_URL=http://users:${PORT_USERS}
      - RESULTS_URL=http://results:${PORT_RESULTS}
    ports:
      - "${PORT_PRODES}:${PORT_PRODES}"
    depends_on:
      - db
      - users
      - sessions
      - results

  groups:
    build:
      context: ./groups
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT_GROUPS}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - USERS_SERVICE_URL=http://users:${PORT_USERS}
    ports:
      - "${PORT_GROUPS}:${PORT_GROUPS}"
    depends_on:
      - db
      - users

  drivers:
    build:
      context: ./drivers
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT_DRIVERS}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "${PORT_DRIVERS}:8051"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
